language: c++

compiler:
  - clang
  - gcc

cache:
  apt: true

# Disallowing packages: libcomedi-dev, libcommoncpp2-dev, libomniorb4-dev, libpqxx-dev
# If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
#sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "KrqAnUjd5+AjMOGnWvtyt0BF0BIkJMwJ0i/4X+VdI3sWYDy4rKZETh4uZLfgQmxBFHbQqCGLSdhM+Mbjt2LF/F5L1GqJELjXMYPxfiaXy2o1KJPZGYAn8Lm/FeTh2GPBkvHAOYrNpY758zKibZeTuIrr7fTiei8iRxELdtXRx/zNKyF3AacuqULrlziaQaUjJWaamwtbLuXWxJ2SsKq0cWNVwhp/SYLBvn4oZ5d6hWZWHav4mGo793nANKN4b6/0iLxOZVxBwdxE8o4bAgqs8Q+mTAeqJ19STCgq9unIMU8QvE5xu/PlR3Z1qJJRBTl3l8eiitW5y92DoJHj6AR3vit7YTTaXSD570CW+p5ZV9e+u/5s3nAZa5S1Qyk4mlEzDxDYv/3HoItC4Llqz3LqBhMHRf0i6ELBzOmsHRoWrG8ANSu5QhilepNbi73NQgp9mOoV7WtlfN/q1Vn3RCCWOb4ZIXEQPhmI9yLbDHOigzKvr2Oe/WSN5aitFBb49alaWzLsObuSVsPOnKfCBKQqqmai7O8asCIWA+FhSeKev7LKgKicK+dGF/Rwdp309MPghBXCiN5uH1AN4D350hIyvOHhC2ZrWgHqXPOjaRwo+J26oX9SFahOopZ/dfLxGyf1R3uX2Ao2AIm2gN0VSTuh41obocVE1pV8SOgF0olzRU8="

before_install:
  - sudo apt-get install libcomedi-dev libcommoncpp2-dev libmysqlclient-dev libomniorb4-dev libpqxx3-dev librrd-dev libsigc++-2.0-dev libsqlite3-dev python-dev

before_script:
  - autoreconf -fiv
  - ./configure --disable-tests

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make && make check ; fi


addons:
#  apt:
#    packages:
#      - libcomedi-dev
#      - libcommoncpp2-dev
#      - libmysqlclient-dev
#      - libomniorb4-dev
#      - libpqxx-dev
#      - librrd-dev
#      - libsigc++-2.0-dev
#      - libsqlite3-dev
#      - python-dev
  coverity_scan:
    project:
      name: "Etersoft/uniset2"
      description: "UniSet2 build submitted via Travis CI"
    notification_email: lav@etersoft.ru
    build_command_prepend: "./configure --disable-tests; make clean"
    build_command: make -j4
    branch_pattern: coverity_scan
